apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-test
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-test-0.zookeeper.default.svc.cluster.local:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
          image: bitnami/kafka:latest
          imagePullPolicy: Always
          name: kafka
          ports:
            - containerPort: 9092
              name: service
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate

